spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picpay_db
    username: root
    password: 123

jpa:
  hibernate.ddl-auto: update
  show-sql: true
  generate-ddl: true

app.authorizationApi: https://run.mocky.io/v3/9b89b419-a2f7-4885-aa86-5ddcea24d520
