version: '3.1'

services:
  backend:
    build:
      dockerfile: ./Dockerfile
      context: ../
    container_name: app
    links:
      - db
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/picpay_db
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
  db:
    image: mysql:8.0.31
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: picpay_db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80

volumes:
  dbbase:

